# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "public_network"
  config.vm.box = "puppetlabs/ubuntu-16.04-64-puppet"
  config.vm.hostname = "zookeeper-1"

end
