# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "public_network"
  config.vm.box = "puppetlabs/ubuntu-16.04-64-puppet"
  config.vm.hostname = "pserver"
  config.vm.synced_folder "./data", "/data"
  config.vm.provider "virtualbox" do |vb|
    vb.customize [
                     "modifyvm", :id,
                     "--memory", "2048",
                     "--paravirtprovider", "kvm", # for linux guest
                     "--cpus", "2"
                 ]
  end

  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "puppet/environments"
    puppet.environment = "dev"
    puppet.manifests_path = "puppet/environments/dev/manifests"
    puppet.manifest_file = "default.pp"
  end

end
